### ISSUE TITLE
Very slow installation

### ISSUE THREAD

**Issue by Ando-git-hub** [mhassan1/redis-memory-server#12]
Hi all, thanks for such a cool lib. 
But I have a problem, my module installation on Linux is very slow.
How can I fix it?

My Node version:` 16.15.1`
      NPM version: `8.12.2`

It freezes at a step that is shown in the picture bellow
  
![Screenshot from 2022-09-05 19-38-02](https://user-images.githubusercontent.com/57172439/188483297-c8b7ed8b-0127-4829-a333-48467ba29b03.png)

But it was successfully installed and I can use it as well, my problem is very slow installation.

Thanks in advance.

**Comment by mhassan1** [comment]
Unfortunately, Redis does not publish pre-compiled binaries for different systems, so this library uses `make` to build from source. On my machine (MacOS), it takes a few minutes, as well, but I only incur that cost on the first installation, so it's not such a problem, for me.

**Comment by platoyuval** [comment]
Hey Marc
The problem is, unlike a MacOS, with CI/CD systems such as Github the package downloads redis server every single time. There is no one time caching of the binaries.

**Comment by bigman73** [comment]
Hey Marc
The problem is, unlike a MacOS, with CI/CD systems such as Github the package downloads redis server every single time the pipeline runs. There is no one time caching of the binaries.

**Comment by mhassan1** [comment]
@bigman73! I think that's a general CI problem with all dependencies. All CI systems should cache `node_modules` and similar.

**Comment by platoyuval** [comment]
I guess it is, but even the initial download is heavily throttled by Github.
For now I had to not use redis-memory-server, as much as I like it when it runs locally.

**Comment by bigman73** [comment]
just an idea - what if the npm package had the compiled binary pre-built into it, for some well know architectures?

**Comment by mhassan1** [comment]
It would be nice if Redis (or some other trustworthy party) built and hosted binaries for some well-known architectures. Then this package could take advantage of that.

**Comment by mhassan1** [comment]
@diegoceldran There are a few reasons why I don't want to do that:
1. Redis Stack has a different license than OSS Redis (https://redis.io/legal/licenses)
2. Redis Stack may go away or change its packaging
3. It means maintaining mappings between OS's and package URLs, which I've seen has been costly for `mongodb-memory-server` (which this library is based on)

I think you have a couple options for skipping auto-install:
1. In CI, you could cache `node_modules/.cache/redis-memory-server` separately, since it will change less often than the rest of `node_modules`
2. In the Docker build, you could create a Docker layer that puts a pre-built `redis-server` binary at `node_modules/.cache/redis-memory-server/redis-binaries/<version>/redis-server`

**Comment by diegoceldran** [comment]
> @diegoceldran There are a few reasons why I don't want to do that:
> 
> 1. Redis Stack has a different license than OSS Redis (https://redis.io/legal/licenses)
> 2. Redis Stack may go away or change its packaging
> 3. It means maintaining mappings between OS's and package URLs, which I've seen has been costly for `mongodb-memory-server` (which this library is based on)
> 
> I think you have a couple options for skipping auto-install:
> 
> 1. In CI, you could cache `node_modules/.cache/redis-memory-server` separately, since it will change less often than the rest of `node_modules`
> 2. In the Docker build, you could create a Docker layer that puts a pre-built `redis-server` binary at `node_modules/.cache/redis-memory-server/redis-binaries/<version>/redis-server`

Thanks for the answer and the advice, I will check it.
