### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null on import

### ISSUE THREAD

**Issue by sameer-hashflow** [mhassan1/redis-memory-server#18]
Hello! I'm trying to use redis-memory-server and when I import it as per below:

```
import { RedisMemoryServer } from 'redis-memory-server';
```

I get this error:

```
    TypeError: Class extends value undefined is not a constructor or null
```

**Comment by mhassan1** [comment]
This appears to be related: https://github.com/isaacs/node-tar/issues/384

**Comment by mhassan1** [comment]
@sameer-hashflow If I remove the [`moduleDirectories`](https://jestjs.io/docs/configuration#moduledirectories-arraystring) configuration from `jest.config.ts` in the reproduction, the issue goes away. I think that setting is causing Jest to find `minipass` in the root of `node_modules`, instead of in the correct `node_modules/tar/node_modules`.
